spring:
  sql:
    init:
      platform: postgres

  datasource:
    url: "jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      show_sql: true
      format_sql: true