spring:
  sql:
    init:
      platform: postgres

  datasource:
    url: "jdbc:postgresql://${DB_HOST:db}:5432/${DB_NAME:bank}"
    username: "${DB_USERNAME:root}"
    password: "${DB_PASSWORD:Ora1626X}"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      show_sql: true
      format_sql: true